Fix output_dir make dependency
Object file targets need to depend on the output_dir target.

Fixes:
make --shuffle=reverse -j1
cc -o obj/mtp_op_truncateobject.o src/mtp_operations/mtp_op_truncateobject.c -c  -I./inc -lpthread -Wall -O3
Assembler messages:
Fatal error: can't create obj/mtp_op_truncateobject.o: No such file or directory
make: *** [Makefile:19: obj/mtp_op_truncateobject.o] Error 1 shuffle=reverse